name: gerador_pmoc
description: App Flutter para gerar PMOC em PDF com logo fixa, marca d'água central e assinatura
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.11.0
  printing: ^5.13.3
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"